### PR TITLE
remove cloudsql proxy

### PR DESCRIPTION
**Pull request by TeamoreA**

### CODE REVIEW

**Review by victortrac — CHANGES_REQUESTED** [review]
Why would you remove cloudsql-proxy from an image that's called `gcloud-cloudsqlproxy-mysql-kubectl`?  If you don't need it, use a different image.

**Comment by victortrac** [comment]
I also don't understand how the presence of the cloudsqlproxy binary has any effect on whether you end up using it or not..?  How does removing it fix anything?

**Comment by TeamoreA** [comment]
> Why would you remove cloudsql-proxy from an image that's called `gcloud-cloudsqlproxy-mysql-kubectl`? If you don't need it, use a different image.

Sure, I should have created a different image. This has been done!

**Comment by TeamoreA** [comment]
> I also don't understand how the presence of the cloudsqlproxy binary has any effect on whether you end up using it or not..? How does removing it fix anything?

Also not sure why this worked but the error I was getting from the script was not super helpful and removing cloudsqlproxy fixed this. see the error from the script below
```
"error": "error",
    "error_description": "The error is unrecognizable."
```

**Review by victortrac — APPROVED** [review]

**Pull request merged**
